### PR TITLE
Adding transitions and making script output cleaner

### PR DESCRIPTION
**Pull request by shelbyKiraM**
Using -webkit-transition to fade colors.
And made output look cleaner: Screenshot
I also made it stars for displaying the rating instead of just a grey box.
And made WARNING go in and out smoother with display: none.

### CODE REVIEW

**Comment by jeticg** [comment]
Hello,
Thank you for your interest in my widget, your support means a lot to me. I have carefully examined the changes you have made, it is absolutely beautiful, but I have decided to take my time to consider whether to apply them or not. It is not a easy decision, please hear me out before going mad at me(which I totally understand).
First, the output cell. The output cell was originally designed for debugging, because in the past I myself had encountered some unexpected outputs, sometimes the users came to me with unexpected displays, I needed a way to diagnose the problem. Putting it on a single cell seemed to me the best option. As you might have noticed in you screenshot, the output information wasn’t incomplete, part of the strings are removed due to the size of the cell. To preserve it’s maintenance and diagnostic value, I am afraid I find it necessary to keep it the way it was.
Second, colour fading. I have considered this design but decided not to do so for one reason: the original design in Evangelion animation was so, smoothing the transaction didn’t seem to fit. This is the same reason why I decided to use grey boxes instead of stars, to me stars didn’t seem fit to the Evangelion theme.
Again, I am very sorry to have come to this decision. This does not mean your effort was a waste, I am sure there are a lot of users would have loved your modifications, just for me personally, they seems unfit at the moment. Should I find them useful in future versions of my widget, I’ll notify you asap.
Thank you for your interest in my widget. Wish you a Happy New Year, cheers!

Yours faithfully, 
Jetic

**Comment by shelbyKiraM** [comment]
Mm, no problem! But what I did to the output was made it "Song Title - Artist - Album - Track # - Rating" from "Song Title~Artist~Album~Track #~Rating" because I like to leave the CLI output up and it was cleaner... It actually doesn't truncate the output text if it is too long, it just overflows outside of the box.

Either way, I like the changes, so I'll use them! I haven't actually watched much of the show, so WTV. It's perty for me! 😸

**Comment by jeticg** [comment]
hello, thanks for the fast reply. The use of ~ instead of - is because some of the songs' information might contain this character, in this case it might cause unexpected results.

**Comment by shelbyKiraM** [comment]
Ah. I know I have some songs that use ~, maybe use some Unicode character? ➖ (emoji dash) or … (Unicode ellipsis) are the first things that comes to mind…

**Pull request closed without merging**
